title: Moritz Podiebrad
logo: /assets/img/profilbild_circle.png
theme: jekyll-theme-minimal
description: "Willkommen auf meiner persönlichen Website! Hier findest du Informationen zu meinen Projekten und mehr."
